#!/bin/bash -
#===============================================================================
#
#          FILE: gen.sh
#
#         USAGE: ./gen.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: 2015年02月03日 13:32
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error


echo "#generated by cxh" > Makefile
echo "" >> Makefile
echo 'CXXFLAGS += -isystem $(GTEST_DIR)/include -g -Wall -Wextra -pthread' >> Makefile
echo "" >> Makefile

echo -n "all: " >>Makefile
for fname in *.cpp; do
    realname=${fname%.*}
    echo -n "$realname " >>Makefile
done

echo "" >>Makefile
echo ".PHONY:all" >>Makefile

echo >> Makefile
for fname in *.cpp; do
    realname=${fname%.*}
    echo "$realname : $fname common.h" >> Makefile
    echo -e "\t"'$(CXX) $(CXXFLAGS) -lpthread -L$(GTEST_DIR) -lgtest_main $< -o $@' >>Makefile
done

echo "" >> Makefile
echo ".PHONY:clean
clean:" >> Makefile

for fname in *.cpp; do
    realname=${fname%.*}
    echo -e "\t-rm -f ${realname}.o $realname" >> Makefile
done

echo "My Leetcode answers: " > README.md
for fname in *.cpp; do
    realname=${fname%.*}
    echo "$realname" >>README.md
done



##generated by cxh

#CPPFLAGS += -isystem $(GTEST_DIR)/include

#CXXFLAGS += -g -Wall -Wextra -pthread

#all:RemoveElement

#RemoveElement:
#RemoveElement : RemoveElement.o
	#$(CXX) $(CXXFLAGS) -lpthread -L$(GTEST_DIR) -lgtest_main $^ -o $@

#RemoveElement.o: common.h $(GTEST_HEADERS)
	#$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c RemoveElement.cpp

#.PHONY:clean
#clean:
	#-rm -f RemoveElement.o RemoveElement

