#!/bin/bash -
#===============================================================================
#
#          FILE: gen.sh
#
#         USAGE: ./gen.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: 2015年02月03日 13:32
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

genMakefile() {
    mkdir -p bin
    echo "#generated by cxh" > Makefile
    echo "" >> Makefile
    echo 'CXXFLAGS += -std=c++11 -isystem $(GTEST_DIR)/include -g -Wall -Wextra -pthread' >> Makefile
    echo "" >> Makefile

    echo -n "all: " >>Makefile
    for fname in *.cpp; do
        realname=${fname%.*}
        echo -n "bin/$realname " >>Makefile
    done

    echo "" >>Makefile
    echo ".PHONY:all" >>Makefile

    echo >> Makefile
    for fname in *.cpp; do
        realname=${fname%.*}
        echo ".PHONY:$realname" >>Makefile
        echo "bin/$realname : $fname ../common.h" >> Makefile
        echo -e "\t"'$(CXX) $(CXXFLAGS) -I.. -lpthread -L$(GTEST_DIR) -lgtest_main $< -o $@' >>Makefile
    done

    echo "" >> Makefile
    echo ".PHONY:clean
    clean:" >> Makefile

    echo -e "\t-rm -f bin/*" >> Makefile
    for fname in *.cpp; do
        realname=${fname%.*}
        echo -e "\t-rm -rf ${realname}.o $realname ${realname}.dSYM " >> Makefile
    done

    echo "My Leetcode answers: " > README.md
    for fname in *.cpp; do
        realname=${fname%.*}
        echo "$realname" >>README.md
    done
}

cd leetcode
genMakefile

cd ../lintcode
genMakefile

##generated by cxh

#CPPFLAGS += -isystem $(GTEST_DIR)/include

#CXXFLAGS += -g -Wall -Wextra -pthread

#all:RemoveElement

#RemoveElement:
#RemoveElement : RemoveElement.o
	#$(CXX) $(CXXFLAGS) -lpthread -L$(GTEST_DIR) -lgtest_main $^ -o $@

#RemoveElement.o: common.h $(GTEST_HEADERS)
	#$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c RemoveElement.cpp

#.PHONY:clean
#clean:
	#-rm -f RemoveElement.o RemoveElement

