#!/bin/bash -
#===============================================================================
#
#          FILE: gen.sh
#
#         USAGE: ./gen.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: 2015年02月03日 13:32
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

flag='-g'
cc='g++'
common='common.h'
echo "
#generated by cxh
" > Makefile

for fname in *.cpp; do
    realname=${fname%.*}
    echo "all:$realname" >>Makefile
done

echo >> Makefile
for fname in *.cpp; do
    realname=${fname%.*}
    echo "$realname:
$realname : ${realname}.o
	$cc $flag -o $realname ${realname}.o

    ${realname}.o: $common
    " >>Makefile
done

echo ".PHONY:clean
clean:" >> Makefile

for fname in *.cpp; do
    realname=${fname%.*}
    echo -e "\t-rm -f ${realname}.o $realname" >> Makefile
done

echo "My Leetcode answers: " > README.md
for fname in *.cpp; do
    realname=${fname%.*}
    echo "$realname" >>README.md
done

#RemoveElement:
#RemoveElement:RemoveElement.o
	#$(cc) $(flag) -o RemoveElement RemoveElement.o

#.PHONY:clean
#clean:
	#-rm -f RemoveElement.o RemoveElement


