
#generated by cxh

all:RemoveElement

RemoveElement:
RemoveElement : RemoveElement.o
	g++ -g -o RemoveElement RemoveElement.o

    RemoveElement.o: common.h
    
.PHONY:clean
clean:
	-rm -f RemoveElement.o RemoveElement
